version: '3.8'

services:
  database:
    image: 'mariadb'
    ports:
      - 3307:3307
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=mydatabase
    restart: always

  go-api:
        build:
            context: .
            dockerfile: Dockerfile
        restart: on-failure
        volumes: 
          - .:/go_app
        environment:
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-password}
            MARIADB_DATABASE: ${MARIADB_DATABASE:-todo}
        ports:
            - "8097:8097"
        depends_on:
            - database
  adminer:
    image: adminer
    restart: always
    ports: 
        - "8080:8080"