version: '3.6'

services:
  database:
    image: 'postgres:11.1-alpine'
    ports:
      - 3307:3307
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRESS_DB: 'db'
    restart: always

  adminer:
    image: adminer:4.8.1
    restart: always
    ports: 
        - "1333:8080"
